# Generated by Django 4.0 on 2022-01-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joinNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField(blank=True, max_length=600)),
                ('CV', models.FileField(upload_to='CV_Files')),
            ],
        ),
    ]
