# Generated by Django 4.0 on 2022-01-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinNowApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinnow',
            name='message',
        ),
    ]
