# Generated by Django 4.0 on 2022-01-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinNowApp', '0002_remove_joinnow_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinnow',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
