# Generated by Django 4.0 on 2022-01-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinNowApp', '0006_alter_joinnow_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinnow',
            name='CV',
            field=models.FileField(upload_to='CV_Files'),
        ),
        migrations.AlterField(
            model_name='joinnow',
            name='phone',
            field=models.CharField(max_length=300),
        ),
    ]
