# Generated by Django 4.0 on 2021-12-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='pic.png', null=True, upload_to='user_img')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='foreFrontApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('area', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Mymensign', 'Mymensign'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Barisal', 'Barisal'), ('Chottogram', 'Chottogram'), ('Khulna', 'Khulna')], max_length=100, null=True)),
                ('houseNo', models.CharField(blank=True, max_length=100, null=True)),
                ('roadNo', models.CharField(blank=True, max_length=100, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foreFrontApp.user')),
            ],
        ),
    ]
