# Generated by Django 4.0 on 2022-01-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreFrontApp', '0005_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image1',
            field=models.ImageField(null=True, upload_to='News/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(null=True, upload_to='News/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image3',
            field=models.ImageField(null=True, upload_to='News/'),
        ),
    ]
